defaults: &defaults
  host: <%= ENV["ELASTICSEARCH_HOST"] || "121.41.4.2:9200" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  host: <%= ENV["ELASTICSEARCH_HOST"] || "121.41.4.2:9200" %>