check_proxy_job:
  cron: "0 */1 * * *"
  class: "Scheduler::CheckProxyJob"
  queue: proxy

archive_proxy_job:
  cron: "*/10 * * * *"
  class: "Scheduler::ArchiveProxyJob"
  queue: proxy

city_price_job:
  cron: "0 23 15 * *"
  class: "Scheduler::CityPriceJob"
  queue: city_price_job