# Options here can still be overridden by cmd line args.
#   sidekiq -C sidekiq.yml
---
:concurrency: <%= ENV["sidekiq_threads"] || 10 %>
:pidfile: tmp/pids/sidekiq.pid
:queues:
  # - [search_indexer, 20]
  - [archive_xici_proxy_job, 1]
  - [check_proxy_ip_job, 2]
  - [archive_gbj_proxy_job, 1]
  - [archive_kuai_proxy_job, 1]
  - [archive_3366_proxy_job, 1]
  - [archive_66_proxy_job, 1]
  - [archive_jxl_proxy_job, 1]
  - [archive_xila_proxy_job, 1]
  - [archive_89_proxy_job, 1]
  - [archive_qy_proxy_job, 1]
  - [proxy, 2]
  - [default, 3]