# Options here can still be overridden by cmd line args.
#   sidekiq -C sidekiq.yml
---
:concurrency: <%= ENV["sidekiq_threads"] || 20 %>
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - [search_indexer, 20]
  - [check_proxy_ip_job, 20]
  - [proxy, 2]
  - [default, 3]